version: '3'
services:
    web:
        build: .
        ports:
        - "8088:80"
        volumes:
          - ./apache-flask:/var/www/apache-flask
        restart: always
        container_name: apache-flask

